---
- name: Ensure redis is installed.
  apt: name=redis-server state=installed

- name: Remove default redis-server.service
  file: path=/etc/systemd/system/redis.service state=absent

- name: Add redis service(s)
  template: src=redis.service.j2
            dest=/etc/systemd/system/redis-{{ item }}.service
            with_items= "{{ redis_names }}"
